name: PromptIQExample
options:
  bundleIdPrefix: com.h9
  deploymentTarget:
    iOS: "17.0"
  createIntermediateGroups: true
  generateEmptyDirectories: true

targets:
  PromptIQExample:
    type: application
    platform: iOS
    sources:
      - path: PromptIQExample
        excludes:
          - "**/.DS_Store"
    settings:
      base:
        TARGETED_DEVICE_FAMILY: "1,2"
        SWIFT_VERSION: "5.0"
        IPHONEOS_DEPLOYMENT_TARGET: "17.0"
        PRODUCT_BUNDLE_IDENTIFIER: com.h9.PromptIQExample
        GENERATE_INFOPLIST_FILE: NO
        ENABLE_PREVIEWS: YES
    info:
      path: PromptIQExample/Info.plist
      properties:
        CFBundleDisplayName: PromptIQ
        CFBundleShortVersionString: "1.0"
        CFBundleVersion: "1"
        LSRequiresIPhoneOS: true
        UILaunchScreen:
          UIColorName: ""
        UIApplicationSceneManifest:
          UIApplicationSupportsMultipleScenes: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UIAppFonts:
          - Posterama2001-Thin.otf
